import type { BrushConfig } from './types'

const BASE: Omit<BrushConfig, 'id' | 'name' | 'preset' | 'tip' | 'hardness' | 'spacing' | 'flow' | 'blendMode'> &
  Partial<BrushConfig> = {
  version: 1,
  category: 'Built-in',
  size: 16,
  minSize: 1,
  color: '#111111',
  opacity: 1,
  scatter: { along: 0, across: 0, seed: 1 },
  stability: 20,
  rotation: 'followPath',
  rotationDegrees: 0,
  pressure: { size: 0.7, opacity: 0, flow: 0.4 },
  stamps: ['dot'],
  stampImages: [],
  seed: 1,
}

export function createBrush(partial: Partial<BrushConfig> = {}): BrushConfig {
  return {
    id: partial.id ?? crypto.randomUUID(),
    version: partial.version ?? 1,
    name: partial.name ?? 'Untitled brush',
    category: partial.category ?? 'Custom',
    preset: partial.preset ?? 'custom',
    tip: partial.tip ?? 'round',
    size: partial.size ?? 16,
    minSize: partial.minSize ?? 1,
    color: partial.color ?? '#111111',
    opacity: partial.opacity ?? 1,
    flow: partial.flow ?? 0.8,
    hardness: partial.hardness ?? 0.85,
    spacing: partial.spacing ?? 4,
    scatter: { along: 0, across: 0, seed: 1, ...partial.scatter },
    stability: partial.stability ?? 20,
    rotation: partial.rotation ?? 'followPath',
    rotationDegrees: partial.rotationDegrees ?? 0,
    blendMode: partial.blendMode ?? 'source-over',
    pressure: { size: 0.7, opacity: 0, flow: 0.4, ...partial.pressure },
    stamps: partial.stamps ? [...partial.stamps] : ['dot'],
    stampImages: partial.stampImages ? [...partial.stampImages] : [],
    seed: partial.seed ?? 1,
  }
}

export function builtinBrushes(): BrushConfig[] {
  return [
    createBrush({
      ...BASE,
      id: 'pen',
      name: 'Pen',
      preset: 'pen',
      tip: 'round',
      size: 6,
      hardness: 1,
      spacing: 2,
      flow: 1,
      pressure: { size: 0.85, opacity: 0, flow: 0.2 },
    }),
    createBrush({
      ...BASE,
      id: 'pencil',
      name: 'Pencil',
      preset: 'pencil',
      tip: 'grain',
      size: 8,
      hardness: 0.55,
      spacing: 3,
      flow: 0.55,
      opacity: 0.85,
      scatter: { along: 0.4, across: 0.6, seed: 3 },
      pressure: { size: 0.4, opacity: 0.8, flow: 0.5 },
    }),
    createBrush({
      ...BASE,
      id: 'marker',
      name: 'Marker',
      preset: 'marker',
      tip: 'oval',
      size: 22,
      hardness: 0.35,
      spacing: 3,
      flow: 0.9,
      blendMode: 'multiply',
      pressure: { size: 0.2, opacity: 0.1, flow: 0.3 },
    }),
    createBrush({
      ...BASE,
      id: 'eraser',
      name: 'Eraser',
      preset: 'eraser',
      tip: 'round',
      size: 24,
      hardness: 0.7,
      spacing: 3,
      flow: 1,
      blendMode: 'erase',
      pressure: { size: 0.5, opacity: 0, flow: 0.4 },
    }),
    createBrush({
      ...BASE,
      id: 'brush',
      name: 'Brush',
      preset: 'brush',
      tip: 'round',
      size: 18,
      hardness: 0.6,
      spacing: 4,
      flow: 0.65,
      pressure: { size: 0.7, opacity: 0.2, flow: 0.6 },
    }),
    createBrush({
      ...BASE,
      id: 'stamp',
      name: 'Stamp',
      preset: 'stamp',
      tip: 'stamp',
      size: 28,
      hardness: 1,
      spacing: 18,
      flow: 1,
      rotation: 'followPath',
    }),
    createBrush({
      ...BASE,
      id: 'soft',
      name: 'Soft brush',
      preset: 'soft',
      tip: 'round',
      size: 32,
      hardness: 0,
      spacing: 6,
      flow: 0.35,
      pressure: { size: 0.5, opacity: 0.4, flow: 0.7 },
    }),
  ]
}
